Mythic+ run history in tooltips
SavedInstances/SavedInstances pull request #476
Opened 2021-02-16 06:42 UTC by ntowle

- Track and show mythic+ run history as relevant for the Great Vault in the SavedInstances tooltip
- Highlights runs which are considered for the Great Vault, and show associated item level
- Consider the "Mythic Keystone" and "Mythic Key Best" rows part of the same category

Examples:
![image](https://user-images.githubusercontent.com/20693723/108027330-ff8d7d00-6ff7-11eb-987e-890d8a5c3d75.png)
![image](https://user-images.githubusercontent.com/20693723/108027408-22b82c80-6ff8-11eb-9ab3-2061b2a21707.png)

2021-02-16 07:59 UTC, LiangYuxuan commented
I would like to store entire weekly run history but showing top 10. Also for `.name` and `.rewardLevel`, add to old table rather than creating one, so we can keep `.mapChallengeModeID`.

2021-02-16 18:28 UTC, ntowle commented
I could not fully re-test because the reset happened. Will hopefully get around to that in the next 24h.

One thing I noticed when testing the reset was the tooltip still shows a reward is waiting directly after claiming from the vault until a /reload or the vault is looked at again, even though C_WeeklyRewards.HasAvailableRewards() reports false. Maybe there's some event to listen to when claiming the weekly reward to trigger a re-check.

2021-02-17 03:36 UTC, LiangYuxuan commented
I can confirm the run history part works well. Since there're not reset yet on CN realm so weekly reward part is not able to test.

2021-02-17 04:09 UTC, LiangYuxuan commented
OKay, I've searched some blz code on PTR and found they use both `WEEKLY_REWARDS_SHOW` and `WEEKLY_REWARDS_UPDATE` to refresh their new map overlay.

Also, when they use their new global string `WEEKLY_REWARDS_RETURN_TO_CLAIM`, they checks on `C_WeeklyRewards.HasAvailableRewards()`, which means it's reward claimed but not selected. And `C_WeeklyRewards.CanClaimRewards()` means it's reward ready to claim.

https://github.com/tomrus88/BlizzardInterfaceCode/blob/7f62c8ace95343e09ca1e42d2d081b6eab950892/Interface/AddOns/Blizzard_WeeklyRewards/Blizzard_WeeklyRewards.lua#L176-L185

```lua
WEEKLY_REWARDS_RETURN_TO_CLAIM = "Return to the Great Vault to Claim your Reward";
```

So I think we should use

```lua
t.MythicKeyBest.rewardWaiting = C_WeeklyRewards_HasAvailableRewards() or C_WeeklyRewards_CanClaimRewards()
```

2021-02-18 05:57 UTC, LiangYuxuan approved these changes

2021-02-18 07:07 UTC, LiangYuxuan requested changes
Take back my approve for still having issue on after claiming weekly reward. I've done a fix for this, by delaying fetching due to no more event is in the claiming process but `WEEKLY_REWARDS_UPDATE`, tested on my alts and it works good. Also I try to make the threshold not hard-coded. This two commit are in my repo and you're free to use it :)

https://github.com/LiangYuxuan/SavedInstances/commit/95a519d0edd41b2628513e3797a15b8337dd41e0

https://github.com/LiangYuxuan/SavedInstances/commit/b274c9fcf9f7ae9ec5acf4f878f5c9a22ce27cbb

2021-02-19 01:49 UTC, LiangYuxuan approved these changes

2021-02-19 02:14 UTC, Stanzilla requested changes
just some small nits, otherwise lgtm!

2021-02-19 02:14 UTC, Stanzilla commented on SavedInstances/Modules/MythicPlus.lua
> +      return left.mapChallengeModeID < right.mapChallengeModeID;
remove ;

2021-02-19 02:14 UTC, Stanzilla commented on SavedInstances/Modules/MythicPlus.lua
> +      return left.level > right.level;
remove ;

2021-02-19 11:12 UTC, Stanzilla requested changes

2021-02-19 18:30 UTC, Stanzilla approved these changes

2021-02-19 18:30 UTC, Stanzilla commented
Awesome, thank you!

2021-02-19 18:31 UTC, merged