feat: Show Primal Core in one line + Tooltips
SavedInstances/SavedInstances pull request #666
Opened 2023-01-01 02:20 UTC by Fia3D

![image](https://user-images.githubusercontent.com/103204902/210159325-d243fa1b-6170-4c68-8515-eaefbd94dd24.png)
![image](https://user-images.githubusercontent.com/103204902/210159326-643153a2-68cd-405f-86d2-38f6509d58b8.png)

2023-01-01 04:04 UTC, LiangYuxuan requested changes
Thank you! Mainly on localization issues to solve.

2023-01-01 04:04 UTC, LiangYuxuan commented on SavedInstances/Core/Core.lua
> +  }
Use localize string like `L["Earth"]` to allow localization.

2023-01-01 04:04 UTC, LiangYuxuan commented on SavedInstances/Core/Core.lua
> +      t.Progress[index][questID] and GREENFONT .. L["Obtained"] .. FONTEND or "Unobtained"
Use global string. https://github.com/SavedInstances/SavedInstances/blob/92142fcd6a380cfcaa8c1019e042578afed8983d/SavedInstances/Core/Core.lua#L2412-L2413

2023-01-01 04:04 UTC, LiangYuxuan commented on SavedInstances/Modules/Progress.lua
> +end
I'd prefer use number progress like `1/4` as first letter abbr is hard to localize and understand in other languages.

2023-01-01 12:51 UTC, Fia3D commented
> Thank you! Mainly on localization issues to solve.

I have fixed everything you have pointed, thank you

2023-01-01 12:56 UTC, LiangYuxuan submitted a review, later dismissed

2023-01-01 21:41 UTC, Stanzilla commented
Looks good but needs a rebase now!

2023-01-01 22:18 UTC, Fia3D commented
> Looks good but needs a rebase now!

Done

2023-01-02 01:34 UTC, Stanzilla approved these changes

2023-01-02 01:34 UTC, merged